### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by EmadFani** [n1arash/ngBestoon#2]
سلام داداش خسته نباشید 
ببخشید من فورک زدم از پروژهتون ولی کلا هیچی درست کار نمیکنه میشه درمورد فایل ها راهنمایی کنید میخوام متریال دیزاینش کنم ممنون

**Comment by jadijadi** [comment]
سلام عماد. اصطلاح «کلا هیچی درست کار نمی کنه» خب خیلی غیر فنی است و در
نتیجه نمی شه کامنتی داد. ریدمی که صفحه اول دیده می شه راهنمای نصب داره و یک
فایل api هم هست که ای پی آی ها رو نوشتیم توش. اگر نیست بگو درست کنم‌(:

2017-01-27 3:57 GMT+03:30 Emad Fani <notifications@github.com>:

**Comment by EmadFani** [comment]
سلام رید می هست ولی ای پی آی ها توش نیست 😅 کلا شاید هم مشکل از منه شاید نمیدونم 
خب اگه میشه ریدمی رو درستش کنید یا هم پروژه وب رو براتون میفرستم خودتون با ای پی آی ها هماهنگ کنید ؟

**Comment by jadijadi** [comment]
آی پی؟ همون bestoon.ir است اگر می خوای به سرور اصلی وصل بشی. و البته منطقی
اینه که روی یک سیستم لوکال کار کنی و فقط برای ریلیز اصلی بری سراغ اون

2017-01-27 16:42 GMT+03:30 Emad Fani <notifications@github.com>:

**Comment by n1arash** [comment]
عماد جان تنها جیزی که نیاز هست برای راه اندازیش اینه که ریپو رو کلون کنی و پکیج هاشو نصب کنی و بعد با 
Angular-cli سرور رو را بندازی :
```
npm install 
ng serve
```

**Comment by EmadFani** [comment]
سلام جادی جان خسته نباشید راستش کسی نتونست این سوالمو جواب بده کلا هم
برنامه نویس زیاد نمیشناسم لطفا اگه میتونید کمک کنید یه راهنمایی چیزی
برسونید ممنون :
 یه پروژه دارم که یه لانچره که یه اپلیکیشن رو آپدیت میکنه (بدون دانلود مجدد
کل اپ) به نظرتون ممکنه با md5 گرفتن از فایل ها انجامش بدم _ بعد نصب اپ چیزی
هم عوض میشه ؟ اگه نه پس اینستالر دقیقا چکار میکنه؟

اپلیکیشن تحت ویندوزه
